### ISSUE TITLE
Training Backward propagation is slow

### ISSUE THREAD

**Issue by clockw** [anton-jeran/MESH2IR#4]
Hi, I am trying to reproduce the mesh2ir following the training parts. However, I found that the backward step is quite slow. 
I tried cuda11.0 / cuda 10.2 and added torch.backends.cudnn.benchmark = True.
For batch size=256, it takes about **5 seconds** for 1 batch training (includes 3 generation steps, which are the most time-consuming). **(GPU is V100)**
Could you please let me know if this is reasonable or if there is anything I need to modify?

**Comment by anton-jeran** [comment]
Hi,

My code is CPU intensive therefore I set number of workers to 32 [line 14[ (https://github.com/anton-jeran/MESH2IR/blob/main/train/MESH2IR/cfg/RIR_s1.yml). If your machine does not have many CPUs, you may reduce number of workers and check. As I remember I trained only using 2 GPUs and it took 20 minutes per epoch and my model need to be trained for 150-200 epochs (around 2 days). Since it is CPU intensive, having more GPUs may not reduce the time of training. You may try using trained model given in the repo. The trained model seems to work reasonable in completely new data (check MESH2IR videos in this website https://anton-jeran.github.io/Listen2Scene/)

**Comment by clockw** [comment]
Thanks for replying! I have tried to use more CPU workers according to my CPUs but it is still slow. May I know your GPU and CPU type, and CUDA/cudnn version if available?

**Comment by anton-jeran** [comment]
![machine](https://github.com/anton-jeran/MESH2IR/assets/73730558/6c017f25-0b75-4141-86a9-6bf8eee897db)
